// WeatherGPT Multilingual Localization Engine (10 Languages)
export const SUPPORTED_LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', voiceCode: 'en-US', flag: '🌐' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', voiceCode: 'ta-IN', flag: '🇮🇳' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', voiceCode: 'hi-IN', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', voiceCode: 'te-IN', flag: '🇮🇳' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', voiceCode: 'bn-IN', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', voiceCode: 'mr-IN', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', voiceCode: 'gu-IN', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', voiceCode: 'kn-IN', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', voiceCode: 'ml-IN', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', voiceCode: 'pa-IN', flag: '🇮🇳' },
];

export const TRANSLATIONS = {
  en: {
    appTitle: 'WeatherGPT',
    appSubtitle: 'Conversational AI for Weather Forecasting, Early Warnings & Climate Intelligence',
    statusOnline: 'Live NWP Systems Connected',
    searchPlaceholder: 'Ask WeatherGPT anything... (e.g. "Will it rain in Chennai tomorrow?", "Crop advisory for rice")',
    voiceListening: 'Listening to your voice...',
    voiceSpeak: 'Read Aloud',
    voiceStop: 'Stop Voice',
    sourcesBadge: '3 Meteorological Sources Active',
    source1: 'Open-Meteo NWP (GFS / ECMWF / WRF)',
    source2: 'Global Air Quality Telemetry (WAQI)',
    source3: 'RainViewer Live Radar GIS Stream',
    quickQuestions: 'Quick Weather Inquiries',
    exportBulletin: 'Export Weather Bulletin',
    apiSettings: 'API & Model Settings',
    currentLocation: 'Detecting Location...',
    tabs: {
      chat: 'AI Weather Chat',
      radar: 'Live GIS Radar & Satellite',
      decision: 'Decision Support Suites',
      climate: 'Climate & NWP Analytics',
    },
    sectors: {
      agriculture: '🌾 Agriculture & Farmers',
      aviation: '✈️ Aviation METAR/TAF',
      marine: '🌊 Marine & Fishermen',
      smartCity: '🏙️ Smart City & Disaster',
      climateAnalytics: '🔬 Climate Trend Analytics',
    },
    weatherParams: {
      temperature: 'Temperature',
      feelsLike: 'Feels Like',
      humidity: 'Humidity',
      windSpeed: 'Wind Speed',
      pressure: 'Pressure',
      uvIndex: 'UV Index',
      rainProb: 'Rain Probability',
      cloudCover: 'Cloud Cover',
      airQuality: 'Air Quality Index',
      visibility: 'Visibility',
      dewPoint: 'Dew Point',
      soilTemp: 'Soil Temperature',
    },
    alertLevels: {
      red: 'RED ALERT - Severe Danger',
      orange: 'ORANGE ALERT - Be Prepared',
      yellow: 'YELLOW ALERT - Be Aware',
      green: 'GREEN - Normal Weather',
    },
    prompts: [
      'Will it rain in Chennai over the next 48 hours?',
      'Agricultural crop advisory for paddy and soil moisture status',
      'Aviation weather briefing: METAR, cloud ceiling and crosswinds',
      'Marine high-seas advisory and wave height for fishermen',
      '10-year historical climate temperature anomaly comparison',
    ]
  },
  ta: {
    appTitle: 'வெதர் ஜிபிடி (WeatherGPT)',
    appSubtitle: 'வானிலை முன்னறிவிப்பு, பேரிடர் எச்சரிக்கைகள் மற்றும் காலநிலைக்கான AI உரையாடல் தளம்',
    statusOnline: 'நேரலை வானிலை மாதிரிகள் இணைக்கப்பட்டுள்ளன',
    searchPlaceholder: 'வானிலை குறித்து கேளுங்கள்... (எ.கா: "சென்னையில் நாளை மழை பெய்யுமா?", "நெல் பயிர் ஆலோசனை")',
    voiceListening: 'உங்கள் குரலைக் கேட்கிறது...',
    voiceSpeak: 'குரலில் வாசி',
    voiceStop: 'குரலை நிறுத்து',
    sourcesBadge: '3 வானிலை தரவு ஆதாரங்கள் செயல்படுகின்றன',
    source1: 'ஓபன்-மீட்டியோ NWP (GFS / ECMWF)',
    source2: 'காற்று தர கண்காணிப்பு (WAQI)',
    source3: 'நேரலை ரேடார் செயற்கைக்கோள்',
    quickQuestions: 'விரைவு வானிலை வினாக்கள்',
    exportBulletin: 'வானிலை அறிக்கையை பதிவிறக்கு',
    apiSettings: 'API & மாதிரி அமைப்புகள்',
    currentLocation: 'இடத்தை கண்டறிகிறது...',
    tabs: {
      chat: 'AI வானிலை உரையாடல்',
      radar: 'நேரலை ரேடார் & செயற்கைக்கோள் வரைபடம்',
      decision: 'துறைசார் முடிவு வழிகாட்டி',
      climate: 'காலநிலை & NWP ஆய்வுகள்',
    },
    sectors: {
      agriculture: '🌾 வேளாண்மை & விவசாயிகள்',
      aviation: '✈️ விமானப் போக்குவரத்து (METAR/TAF)',
      marine: '🌊 கடல் & மீனவர் பாதுகாப்பு',
      smartCity: '🏙️ ஸ்மார்ட் சிட்டி & பேரிடர் மேலாண்மை',
      climateAnalytics: '🔬 காலநிலை மாற்ற போக்குகள்',
    },
    weatherParams: {
      temperature: 'வெப்பநிலை',
      feelsLike: 'உணரும் வெப்பம்',
      humidity: 'ஈரப்பதம்',
      windSpeed: 'காற்றின் வேகம்',
      pressure: 'காற்றழுத்தம்',
      uvIndex: 'புற ஊதா குறியீடு (UV)',
      rainProb: 'மழைக்கான வாய்ப்பு',
      cloudCover: 'மேக மூட்டம்',
      airQuality: 'காற்று தரம் (AQI)',
      visibility: 'பார்வை தூரம்',
      dewPoint: 'பனி நிலை புள்ளி',
      soilTemp: 'மண் வெப்பநிலை',
    },
    alertLevels: {
      red: 'சிவப்பு எச்சரிக்கை (Red Alert) - தீவிர ஆபத்து',
      orange: 'ஆரஞ்சு எச்சரிக்கை (Orange Alert) - தயாராக இருங்கள்',
      yellow: 'மஞ்சள் எச்சரிக்கை (Yellow Alert) - விழிப்புடன் இருங்கள்',
      green: 'பச்சை (Green) - இயல்பான வானிலை',
    },
    prompts: [
      'சென்னையில் அடுத்த 48 மணி நேரத்தில் மழை பெய்யுமா?',
      'விவசாயிகளுக்கான பயிர் பாதுகாப்பு மற்றும் மண் ஈரப்பதம் ஆலோசனை',
      'விமான வானிலை தகவல்: பார்வை தூரம் மற்றும் மேக மூட்டம்',
      'மீனவர்களுக்கான கடல் அலை உயரம் மற்றும் காற்று எச்சரிக்கை',
      'கடந்த 10 ஆண்டு காலநிலை வெப்பநிலை மாறுபாடு ஆய்வு',
    ]
  },
  hi: {
    appTitle: 'वेदर जीपीटी (WeatherGPT)',
    appSubtitle: 'मौसम पूर्वानुमान, आपदा चेतावनी और जलवायु विश्लेषण हेतु संवादात्मक AI मंच',
    statusOnline: 'सक्रिय मौसम पूर्वानुमान मॉडल जुड़े हैं',
    searchPlaceholder: 'वेदर जीपीटी से कुछ भी पूछें... (उदा: "क्या कल दिल्ली में बारिश होगी?", "गेहूं फसल सलाह")',
    voiceListening: 'आपकी आवाज सुनी जा रही है...',
    voiceSpeak: 'आवाज में सुनें',
    voiceStop: 'रोकें',
    sourcesBadge: '3 मौसम डेटा स्रोत सक्रिय',
    source1: 'ओपन-मीटिओ NWP (GFS / ECMWF)',
    source2: 'वायु गुणवत्ता सूचकांक (WAQI)',
    source3: 'लाइव रडार व उपग्रह डेटा',
    quickQuestions: 'त्वरित मौसम प्रश्न',
    exportBulletin: 'मौसम बुलेटिन डाउनलोड करें',
    apiSettings: 'API व मॉडल सेटिंग्स',
    currentLocation: 'स्थान खोजा जा रहा है...',
    tabs: {
      chat: 'AI मौसम चैट',
      radar: 'लाइव GIS रडार व उपग्रह',
      decision: 'निर्णय समर्थन प्रणाली',
      climate: 'जलवायु व NWP विश्लेषण',
    },
    sectors: {
      agriculture: '🌾 कृषि एवं किसान सलाह',
      aviation: '✈️ विमानन मौसम (METAR/TAF)',
      marine: '🌊 समुद्री व मछुआरा चेतावनी',
      smartCity: '🏙️ स्मार्ट सिटी व आपदा प्रबंधन',
      climateAnalytics: '🔬 जलवायु परिवर्तन रुझान',
    },
    weatherParams: {
      temperature: 'तापमान',
      feelsLike: 'अनुभूत तापमान',
      humidity: 'आर्द्रता',
      windSpeed: 'हवा की गति',
      pressure: 'वायुमंडलीय दबाव',
      uvIndex: 'यूवी इंडेक्स',
      rainProb: 'वर्षा की संभावना',
      cloudCover: 'बादलों का आवरण',
      airQuality: 'वायु गुणवत्ता (AQI)',
      visibility: 'दृश्यता',
      dewPoint: 'ओस बिंदु',
      soilTemp: 'मिट्टी का तापमान',
    },
    alertLevels: {
      red: 'रेड अलर्ट - गंभीर खतरा',
      orange: 'ऑरेंज अलर्ट - तैयार रहें',
      yellow: 'येलो अलर्ट - सतर्क रहें',
      green: 'ग्रीन - सामान्य मौसम',
    },
    prompts: [
      'क्या अगले 48 घंटों में दिल्ली में बारिश होगी?',
      'किसानों के लिए फसल सुरक्षा और मिट्टी की नमी संबंधी सलाह',
      'विमानन मौसम सारांश: दृश्यता और हवा की दिशा',
      'मछुआरों के लिए समुद्र में लहरों की ऊंचाई और चेतावनी',
      'पिछले 10 वर्षों के तापमान और जलवायु रुझान का विश्लेषण',
    ]
  },
  te: {
    appTitle: 'వెదర్ జీపీటీ (WeatherGPT)',
    appSubtitle: 'వాతావరణ సూచనలు, విపత్తు హెచ్చరికలు మరియు శీతోష్ణస్థితి విశ్లేషణ కోసం సంభాషణా AI ప్లాట్‌ఫాం',
    statusOnline: 'రియల్-టైమ్ వాతావరణ నమూనాలు అనుసంధానించబడ్డాయి',
    searchPlaceholder: 'వాతావరణ సమాచారం కోసం అడగండి... (ఉదా: "హైదరాబాద్‌లో రేపు వర్షం పడుతుందా?")',
    voiceListening: 'వాయిస్ వినబడుతోంది...',
    voiceSpeak: 'వినండి',
    voiceStop: 'ఆపండి',
    sourcesBadge: '3 వాతావరణ డేటా వనరులు క్రియాశీలంగా ఉన్నాయి',
    source1: 'ఓపెన్-మీటియో NWP (GFS / ECMWF)',
    source2: 'గాలి నాణ్యత సూచిక (WAQI)',
    source3: 'లైవ్ రాడార్ & శాటిలైట్',
    quickQuestions: 'త్వరిత ప్రశ్నలు',
    exportBulletin: 'వాతావరణ బులెటిన్ డౌన్‌లోడ్',
    apiSettings: 'API & సెట్టింగ్‌లు',
    currentLocation: 'స్థానాన్ని గుర్తిస్తోంది...',
    tabs: {
      chat: 'AI వాతావరణ చాట్',
      radar: 'లైవ్ GIS రాడార్ మ్యాప్',
      decision: 'నిర్ణయ మద్దతు వ్యవస్థ',
      climate: 'శీతోష్ణస్థితి విశ్లేషణ',
    },
    sectors: {
      agriculture: '🌾 వ్యవసాయం & రైతుల సలహాలు',
      aviation: '✈️ ఏవియేషన్ వెదర్ (METAR)',
      marine: '🌊 సముద్ర & మత్స్యకార భద్రత',
      smartCity: '🏙️ స్మార్ట్ సిటీ & విపత్తు నిర్వహణ',
      climateAnalytics: '🔬 శీతోష్ణస్థితి ధోరణులు',
    },
    weatherParams: {
      temperature: 'ఉష్ణోగ్రత',
      feelsLike: 'అనిపించే ఉష్ణోగ్రత',
      humidity: 'తేమ శాతం',
      windSpeed: 'గాలి వేగం',
      pressure: 'పీడనం',
      uvIndex: 'UV ఇండెక్స్',
      rainProb: 'వర్షం పడే అవకాశం',
      cloudCover: 'మేఘాల కవరేజ్',
      airQuality: 'గాలి నాణ్యత (AQI)',
      visibility: 'దృశ్యమానత',
      dewPoint: 'మంచు బిందువు',
      soilTemp: 'నేల ఉష్ణోగ్రత',
    },
    alertLevels: {
      red: 'రెడ్ అలర్ట్ - తీవ్ర ప్రమాదం',
      orange: 'ఆరెంజ్ అలర్ట్ - సిద్ధంగా ఉండండి',
      yellow: 'ఎల్లో అలర్ట్ - అప్రమత్తంగా ఉండండి',
      green: 'గ్రీన్ - సాధారణ వాతావరణం',
    },
    prompts: [
      'హైదరాబాద్‌లో రాబోయే 48 గంటల్లో వర్షం కురుస్తుందా?',
      'వరి పంట రక్షణ మరియు నేల తేమపై రైతు సలహా',
      'మత్స్యకారుల కోసం సముద్ర అలల ఎత్తు మరియు గాలి హెచ్చరిక',
      'విమానయాన వాతావరణం: దృశ్యమానత మరియు క్లౌడ్ సీలింగ్',
    ]
  },
  bn: {
    appTitle: 'ওয়েদার জিপিটি (WeatherGPT)',
    appSubtitle: 'আবহাওয়ার পূর্বাভাস, দুর্যোগ সতর্কতা এবং জলবায়ু বিশ্লেষণের জন্য এআই প্ল্যাটফর্ম',
    statusOnline: 'রিয়েল-টাইম আবহাওয়া মডেল সক্রিয়',
    searchPlaceholder: 'আবহাওয়া সম্পর্কে জিজ্ঞাসা করুন... (যেমন: "কলকাতায় কি কাল বৃষ্টি হবে?")',
    voiceListening: 'আপনার কণ্ঠস্বর শুনছি...',
    voiceSpeak: 'পড়ে শোনান',
    voiceStop: 'থামুন',
    sourcesBadge: '৩টি আবহাওয়া ডেটা সোর্স সক্রিয়',
    source1: 'ওপেন-মিটিও NWP (GFS / ECMWF)',
    source2: 'বায়ুর মান সূচক (WAQI)',
    source3: 'লাইভ রাডার ও স্যাটেলাইট',
    quickQuestions: 'দ্রুত আবহাওয়া প্রশ্ন',
    exportBulletin: 'আবহাওয়া বুলেটিন ডাউনলোড',
    apiSettings: 'API ও মডেল সেটিংস',
    currentLocation: 'অবস্থান নির্ণয় করা হচ্ছে...',
    tabs: {
      chat: 'AI আবহাওয়া চ্যাট',
      radar: 'লাইভ GIS রাডার ম্যাপ',
      decision: 'সিদ্ধান্ত সহায়তা ব্যবস্থা',
      climate: 'জলবায়ু ও NWP বিশ্লেষণ',
    },
    sectors: {
      agriculture: '🌾 কৃষি ও কৃষক পরামর্শ',
      aviation: '✈️ বিমান চলাচল আবহাওয়া',
      marine: '🌊 সামুদ্রিক ও মৎস্যজীবী সতর্কতা',
      smartCity: '🏙️ স্মার্ট সিটি ও দুর্যোগ ব্যবস্থাপনা',
      climateAnalytics: '🔬 জলবায়ু পরিবর্তনের ধারা',
    },
    weatherParams: {
      temperature: 'তাপমাত্রা',
      feelsLike: 'অনুভূত তাপমাত্রা',
      humidity: 'আর্দ্রতা',
      windSpeed: 'বাতাসের গতি',
      pressure: 'বায়ুমণ্ডলীয় চাপ',
      uvIndex: 'ইউভি ইনডেক্স',
      rainProb: 'বৃষ্টির সম্ভাবনা',
      cloudCover: 'মেঘের ঘনত্ব',
      airQuality: 'বায়ুর মান (AQI)',
      visibility: 'দৃশ্যমানতা',
      dewPoint: 'শিশিরাঙ্ক',
      soilTemp: 'মাটির তাপমাত্রা',
    },
    alertLevels: {
      red: 'রেড অ্যালার্ট - চরম বিপদ',
      orange: 'অরেঞ্জ অ্যালার্ট - প্রস্তুত থাকুন',
      yellow: 'ইয়েলো অ্যালার্ট - সতর্ক থাকুন',
      green: 'গ্রিন - স্বাভাবিক আবহাওয়া',
    },
    prompts: [
      'কলকাতায় আগামী ৪৮ ঘণ্টায় কি বৃষ্টি হবে?',
      'কৃষকদের জন্য ফসল সুরক্ষা ও মাটির আর্দ্রতা সংক্রান্ত পরামর্শ',
      'মৎস্যজীবীদের জন্য সমুদ্রের ঢেউ ও বাতাসের সতর্কতা',
      'বিগত ১০ বছরের জলবায়ু পরিবর্তনের বিশ্লেষণ',
    ]
  },
  mr: {
    appTitle: 'वेदर जीपीटी (WeatherGPT)',
    appSubtitle: 'हवामान अंदाज, आपत्ती इशारे आणि हवामान विश्लेषणासाठी संवादात्मक AI प्लॅटफॉर्म',
    statusOnline: 'रिअल-टाइम हवामान मॉडेल्स जोडले आहेत',
    searchPlaceholder: 'हवामानाबद्दल काहीही विचारा... (उदा: "पुण्यात उद्या पाऊस पडेल का?")',
    voiceListening: 'आवाज ऐकत आहे...',
    voiceSpeak: 'ऐका',
    voiceStop: 'थांबवा',
    sourcesBadge: '३ हवामान डेटा स्रोत सक्रिय',
    source1: 'ओपन-मीटिओ NWP (GFS / ECMWF)',
    source2: 'हवेची गुणवत्ता (WAQI)',
    source3: 'थेट रडार आणि उपग्रह',
    quickQuestions: 'जलद हवामान प्रश्न',
    exportBulletin: 'हवामान बुलेटिन डाउनलोड करा',
    apiSettings: 'API व मॉडेल सेटिंग्ज',
    currentLocation: 'स्थान शोधत आहे...',
    tabs: {
      chat: 'AI हवामान संवाद',
      radar: 'थेट GIS रडार नकाशा',
      decision: 'निर्णय समर्थन प्रणाली',
      climate: 'हवामान व NWP विश्लेषण',
    },
    sectors: {
      agriculture: '🌾 कृषी व शेतकरी सल्ला',
      aviation: '✈️ विमान वाहतूक हवामान',
      marine: '🌊 सागरी व मच्छिमार सुरक्षा',
      smartCity: '🏙️ स्मार्ट सिटी व आपत्ती व्यवस्थापन',
      climateAnalytics: '🔬 हवामान बदल कल विश्लेषण',
    },
    weatherParams: {
      temperature: 'तापमान',
      feelsLike: 'जाणवणारे तापमान',
      humidity: 'आर्द्रता',
      windSpeed: 'वाऱ्याचा वेग',
      pressure: 'हवेचा दाब',
      uvIndex: 'यूव्ही निर्देशांक',
      rainProb: 'पावसाची शक्यता',
      cloudCover: 'ढगाळ वातावरण',
      airQuality: 'हवेची गुणवत्ता (AQI)',
      visibility: 'दृश्यमानता',
      dewPoint: 'दवबिंदू',
      soilTemp: 'मातीचे तापमान',
    },
    alertLevels: {
      red: 'रेड अलर्ट - तीव्र धोका',
      orange: 'ऑरेंज अलर्ट - तयार राहा',
      yellow: 'यलो अलर्ट - सावध राहा',
      green: 'ग्रीन - सामान्य हवामान',
    },
    prompts: [
      'पुण्यात पुढील ४८ तासांत पाऊस पडेल का?',
      'शेतकऱ्यांसाठी पीक संरक्षण आणि मातीतील ओलावा सल्ला',
      'मच्छिमारांसाठी समुद्रातील लाटांची उंची आणि वाऱ्याचा इशारा',
    ]
  },
  gu: {
    appTitle: 'વેધર જીપીટી (WeatherGPT)',
    appSubtitle: 'હવામાન આગાહી, આપત્તિ ચેતવણીઓ અને આબોહવા વિશ્લેષણ માટે AI પ્લેટફોર્મ',
    statusOnline: 'રીઅલ-ટાઇમ હવામાન મોડલ્સ જોડાયેલા છે',
    searchPlaceholder: 'હવામાન વિશે કંઈપણ પૂછો... (દા.ત: "અમદાવાદમાં કાલે વરસાદ પડશે?")',
    voiceListening: 'તમારો અવાજ સાંભળી રહ્યો છે...',
    voiceSpeak: 'સાંભળો',
    voiceStop: 'રોકો',
    sourcesBadge: '૩ હવામાન ડેટા સ્ત્રોત સક્રિય',
    source1: 'ઓપન-મીટિઓ NWP (GFS / ECMWF)',
    source2: 'હવા ગુણવત્તા સૂચકાંક (WAQI)',
    source3: 'લાઈવ રડાર અને સેટેલાઇટ',
    quickQuestions: 'ઝડપી પ્રશ્નો',
    exportBulletin: 'હવામાન બુલેટિન ડાઉનલોડ',
    apiSettings: 'API સેટિંગ્સ',
    currentLocation: 'સ્થાન શોધાઈ રહ્યું છે...',
    tabs: {
      chat: 'AI હવામાન ચેટ',
      radar: 'લાઈવ GIS રડાર નકશો',
      decision: 'નિર્ણય સહાયક પ્રણાલી',
      climate: 'આબોહવા વિશ્લેષણ',
    },
    sectors: {
      agriculture: '🌾 કૃષિ અને ખેડૂત સલાહ',
      aviation: '✈️ એવિએશન હવામાન',
      marine: '🌊 સમુદ્રી અને માછીમાર ચેતવણી',
      smartCity: '🏙️ સ્માર્ટ સિટી અને આપત્તિ વ્યવસ્થાપન',
      climateAnalytics: '🔬 આબોહવા પરિવર્તન વલણ',
    },
    weatherParams: {
      temperature: 'તાપમાન',
      feelsLike: 'અનુભવાતું તાપમાન',
      humidity: 'ભેજનું પ્રમાણ',
      windSpeed: 'પવનની ગતિ',
      pressure: 'વાયુ દબાણ',
      uvIndex: 'યુવી ઇન્ડેક્સ',
      rainProb: 'વરસાદની સંભાવના',
      cloudCover: 'વાદળોનું આવરણ',
      airQuality: 'હવાની ગુણવત્તા (AQI)',
      visibility: 'દૃશ્યતા',
      dewPoint: 'ઝાકળ બિંદુ',
      soilTemp: 'જમીનનું તાપમાન',
    },
    alertLevels: {
      red: 'રેડ એલર્ટ - ગંભીર ખતરો',
      orange: 'ઓરેન્જ એલર્ટ - તૈયાર રહો',
      yellow: 'યલો એલર્ટ - સાવચેત રહો',
      green: 'ગ્રીન - સામાન્ય હવામાન',
    },
    prompts: [
      'અમદાવાદમાં આગામી ૪૮ કલાકમાં વરસાદની શક્યતા કેટલી છે?',
      'કપાસ અને મગફળી પાક માટે કૃષિ સલાહ',
      'માછીમારો માટે દરિયાઈ મોજાની ઊંચાઈ અને પવન ચેતવણી',
    ]
  },
  kn: {
    appTitle: 'ವೆದರ್ ಜಿಪಿಟಿ (WeatherGPT)',
    appSubtitle: 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ, ವಿಪತ್ತು ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಹವಾಮಾನ ವಿಶ್ಲೇಷಣೆಗಾಗಿ ಸಂವಾದಾತ್ಮಕ AI ವೇದಿಕೆ',
    statusOnline: 'ನೈಜ-ಸಮಯದ ಹವಾಮಾನ ಮಾದರಿಗಳು ಸಂಪರ್ಕಗೊಂಡಿವೆ',
    searchPlaceholder: 'ಹವಾಮಾನದ ಬಗ್ಗೆ ಕೇಳಿ... (ಉದಾ: "ಬೆಂಗಳೂರಿನಲ್ಲಿ ನಾಳೆ ಮಳೆಯಾಗುವುದೇ?")',
    voiceListening: 'ಧ್ವನಿಯನ್ನು ಆಲಿಸಲಾಗುತ್ತಿದೆ...',
    voiceSpeak: 'ಕೇಳಿ',
    voiceStop: 'ನಿಲ್ಲಿಸಿ',
    sourcesBadge: '೩ ಹವಾಮಾನ ಡೇಟಾ ಮೂಲಗಳು ಸಕ್ರಿಯವಾಗಿವೆ',
    source1: 'ಓಪನ್-ಮೀಟಿಯೋ NWP (GFS / ECMWF)',
    source2: 'ವಾಯು ಗುಣಮಟ್ಟ ಸೂಚ್ಯಂಕ (WAQI)',
    source3: 'ಲೈವ್ ರೇಡಾರ್ ಮತ್ತು ಉಪಗ್ರಹ',
    quickQuestions: 'ತ್ವರಿತ ಹವಾಮಾನ ಪ್ರಶ್ನೆಗಳು',
    exportBulletin: 'ಹವಾಮಾನ ಬುಲೆಟಿನ್ ಡೌನ್‌ಲೋಡ್',
    apiSettings: 'API ಮತ್ತು ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    currentLocation: 'ಸ್ಥಳವನ್ನು ಪತ್ತೆಮಾಡಲಾಗುತ್ತಿದೆ...',
    tabs: {
      chat: 'AI ಹವಾಮಾನ ಚಾಟ್',
      radar: 'ಲೈವ್ GIS ರೇಡಾರ್ ನಕ್ಷೆ',
      decision: 'ನಿರ್ಧಾರ ಬೆಂಬಲ ವ್ಯವಸ್ಥೆ',
      climate: 'ಹವಾಮಾನ ಪ್ರವೃತ್ತಿ ವಿಶ್ಲೇಷಣೆ',
    },
    sectors: {
      agriculture: '🌾 ಕೃಷಿ ಮತ್ತು ರೈತರ ಸಲಹೆ',
      aviation: '✈️ ವಾಯುಯಾನ ಹವಾಮಾನ',
      marine: '🌊 ಸಮುದ್ರ ಮತ್ತು ಮೀನುಗಾರರ ಸುರಕ್ಷತೆ',
      smartCity: '🏙️ ಸ್ಮಾರ್ಟ್ ಸಿಟಿ ಮತ್ತು ವಿಪತ್ತು ನಿರ್ವಹಣೆ',
      climateAnalytics: '🔬 ಹವಾಮಾನ ಬದಲಾವಣೆ ಪ್ರವೃತ್ತಿ',
    },
    weatherParams: {
      temperature: 'ತಾಪಮಾನ',
      feelsLike: 'ಅನುಭವವಾಗುವ ತಾಪಮಾನ',
      humidity: 'ಆರ್ದ್ರತೆ',
      windSpeed: 'ಗಾಳಿಯ ವೇಗ',
      pressure: 'ವಾಯುಭಾರ',
      uvIndex: 'ಯುವಿ ಸೂಚ್ಯಂಕ',
      rainProb: 'ಮಳೆಯ ಸಾಧ್ಯತೆ',
      cloudCover: 'ಮೋಡ ಕವಿದ ವಾತಾವರಣ',
      airQuality: 'ವಾಯು ಗುಣಮಟ್ಟ (AQI)',
      visibility: 'ಗೋಚರತೆ',
      dewPoint: 'ಇಬ್ಬನಿ ಬಿಂದು',
      soilTemp: 'ಮಣ್ಣಿನ ತಾಪಮಾನ',
    },
    alertLevels: {
      red: 'ರೆಡ್ ಅಲರ್ಟ್ - ತೀವ್ರ ಅಪಾಯ',
      orange: 'ಆರೆಂಜ್ ಅಲರ್ಟ್ - ಸಿದ್ಧರಾಗಿರಿ',
      yellow: 'ಯೆಲ್ಲೋ ಅಲರ್ಟ್ - ಎಚ್ಚರದಿಂದಿರಿ',
      green: 'ಗ್ರೀನ್ - ಸಾಮಾನ್ಯ ಹವಾಮಾನ',
    },
    prompts: [
      'ಬೆಂಗಳೂರಿನಲ್ಲಿ ಮುಂದಿನ 48 ಗಂಟೆಗಳಲ್ಲಿ ಮಳೆಯಾಗಲಿದೆಯೇ?',
      'ರೈತರಿಗೆ ಬೆಳೆ ರಕ್ಷಣೆ ಮತ್ತು ಮಣ್ಣಿನ ತೇವಾಂಶ ಸಲಹೆ',
      'ಮೀನುಗಾರರಿಗೆ ಸಮುದ್ರ ಅಲೆಗಳ ಎತ್ತರ ಮತ್ತು ಗಾಳಿ ಎಚ್ಚರಿಕೆ',
    ]
  },
  ml: {
    appTitle: 'വെതർ ജിപിടി (WeatherGPT)',
    appSubtitle: 'കാലാവസ്ഥാ പ്രവചനം, ദുരന്ത മുന്നറിയിപ്പുകൾ, കാലാവസ്ഥാ വിശകലനം എന്നിവയ്ക്കുള്ള AI പ്ലാറ്റ്‌ഫോം',
    statusOnline: 'തത്സമയ കാലാവസ്ഥാ മോഡലുകൾ ബന്ധിപ്പിച്ചിരിക്കുന്നു',
    searchPlaceholder: 'കാലാവസ്ഥയെക്കുറിച്ച് ചോദിക്കൂ... (ഉദാ: "കൊച്ചിയിൽ നാളെ മഴ പെയ്യുമോ?")',
    voiceListening: 'ശബ്ദം ശ്രവിക്കുന്നു...',
    voiceSpeak: 'വായിക്കുക',
    voiceStop: 'നിർത്തുക',
    sourcesBadge: '3 കാലാവസ്ഥാ ഡാറ്റാ സ്രോതസ്സുകൾ സജീവം',
    source1: 'ഓപ്പൺ-മീറ്റിയോ NWP (GFS / ECMWF)',
    source2: 'വായു ഗുണനിലവാര സൂചിക (WAQI)',
    source3: 'ലൈവ് റഡാർ & ഉപഗ്രഹ ഡാറ്റ',
    quickQuestions: 'ദ്രുത കാലാവസ്ഥാ ചോദ്യങ്ങൾ',
    exportBulletin: 'കാലാവസ്ഥാ ബുള്ളറ്റിൻ ഡൗൺലോഡ്',
    apiSettings: 'API ക്രമീകരണങ്ങൾ',
    currentLocation: 'സ്ഥലം കണ്ടെത്തുന്നു...',
    tabs: {
      chat: 'AI കാലാവസ്ഥാ ചാറ്റ്',
      radar: 'ലൈവ് GIS റഡാർ മാപ്പ്',
      decision: 'തീരുമാന സഹായ സംവിധാനം',
      climate: 'കാലാവസ്ഥാ വ്യതിയാന വിശകലനം',
    },
    sectors: {
      agriculture: '🌾 കൃഷിയും കർഷക നിർദ്ദേശങ്ങളും',
      aviation: '✈️ വ്യോമയാന കാലാവസ്ഥ',
      marine: '🌊 സമുദ്ര-മത്സ്യത്തൊഴിലാളി മുന്നറിയിപ്പ്',
      smartCity: '🏙️ സ്മാർട്ട് സിറ്റിയും ദുരന്തനിവാരണവും',
      climateAnalytics: '🔬 കാലാവസ്ഥാ മാറ്റ പ്രവണതകൾ',
    },
    weatherParams: {
      temperature: 'താപനില',
      feelsLike: 'അനുഭവപ്പെടുന്ന ചൂട്',
      humidity: 'ഈർപ്പം',
      windSpeed: 'കാറ്റിന്റെ വേഗത',
      pressure: 'വായു മർദ്ദം',
      uvIndex: 'UV ഇൻഡക്സ്',
      rainProb: 'മഴ സാധ്യത',
      cloudCover: 'മേഘാവൃതത',
      airQuality: 'വായു ഗുണനിലവാരം (AQI)',
      visibility: 'ദൃശ്യപരത',
      dewPoint: 'തുഷാര ബിന്ദു',
      soilTemp: 'മണ്ണിന്റെ താപനില',
    },
    alertLevels: {
      red: 'റെഡ് അലർട്ട് - അതീവ ജാഗ്രത',
      orange: 'ഓറഞ്ച് അലർട്ട് - തയ്യാറെടുക്കുക',
      yellow: 'യെല്ലോ അലർട്ട് - ശ്രദ്ധിക്കുക',
      green: 'ഗ്രീൻ - സാധാരണ കാലാവസ്ഥ',
    },
    prompts: [
      'കൊച്ചിയിൽ അടുത്ത 48 മണിക്കൂറിൽ ശക്തമായ മഴയ്ക്ക് സാധ്യതയുണ്ടോ?',
      'കർഷകർക്കുള്ള വിള സംരക്ഷണവും മണ്ണിലെ ഈർപ്പവും സംബന്ധിച്ച നിർദ്ദേശം',
      'മത്സ്യത്തൊഴിലാളികൾക്കുള്ള കടൽക്ഷോഭവും തിരമാല ഉയരവും മുന്നറിയിപ്പ്',
    ]
  },
  pa: {
    appTitle: 'ਵੈਦਰ ਜੀਪੀਟੀ (WeatherGPT)',
    appSubtitle: 'ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ, ਆਫ਼ਤ ਚੇਤਾਵਨੀਆਂ ਅਤੇ ਜਲਵਾਯੂ ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਏਆਈ ਪਲੇਟਫਾਰਮ',
    statusOnline: 'ਰੀਅਲ-ਟਾਈਮ ਮੌਸਮ ਮਾਡਲ ਸਰਗਰਮ ਹਨ',
    searchPlaceholder: 'ਮੌਸਮ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ... (ਉਦਾ: "ਕੀ ਕੱਲ੍ਹ ਅੰਮ੍ਰਿਤਸਰ ਵਿੱਚ ਮੀਂਹ ਪਵੇਗਾ?")',
    voiceListening: 'ਤੁਹਾਡੀ ਆਵਾਜ਼ ਸੁਣ ਰਿਹਾ ਹੈ...',
    voiceSpeak: 'ਸੁਣੋ',
    voiceStop: 'ਰੋਕੋ',
    sourcesBadge: '੩ ਮੌਸਮ ਡੇਟਾ ਸਰੋਤ ਸਰਗਰਮ',
    source1: 'ਓਪਨ-ਮੀਟੀਓ NWP (GFS / ECMWF)',
    source2: 'ਹਵਾ ਦੀ ਗੁਣਵੱਤਾ (WAQI)',
    source3: 'ਲਾਈਵ ਰਾਡਾਰ ਤੇ ਉਪਗ੍ਰਹਿ',
    quickQuestions: 'ਤੁਰੰਤ ਸਵਾਲ',
    exportBulletin: 'ਮੌਸਮ ਬੁਲੇਟਿਨ ਡਾਊਨਲੋਡ',
    apiSettings: 'API ਸੈਟਿੰਗਾਂ',
    currentLocation: 'ਟਿਕਾਣਾ ਲੱਭਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    tabs: {
      chat: 'AI ਮੌਸਮ ਚੈਟ',
      radar: 'ਲਾਈਵ GIS ਰਾਡਾਰ ਨਕਸ਼ਾ',
      decision: 'ਫੈਸਲਾ ਸਹਾਇਤਾ ਪ੍ਰਣਾਲੀ',
      climate: 'ਜਲਵਾਯੂ ਰੁਝਾਨ ਵਿਸ਼ਲੇਸ਼ਣ',
    },
    sectors: {
      agriculture: '🌾 ਖੇਤੀਬਾੜੀ ਅਤੇ ਕਿਸਾਨ ਸਲਾਹ',
      aviation: '✈️ ਹਵਾਬਾਜ਼ੀ ਮੌਸਮ (METAR)',
      marine: '🌊 ਸਮੁੰਦਰੀ ਤੇ ਮਛੇਰਿਆਂ ਦੀ ਸੁਰੱਖਿਆ',
      smartCity: '🏙️ ਸਮਾਰਟ ਸਿਟੀ ਅਤੇ ਆਫ਼ਤ ਪ੍ਰਬੰਧਨ',
      climateAnalytics: '🔬 ਜਲਵਾਯੂ ਤਬਦੀਲੀ ਵਿਸ਼ਲੇਸ਼ਣ',
    },
    weatherParams: {
      temperature: 'ਤਾਪਮਾਨ',
      feelsLike: 'ਮਹਿਸੂਸ ਹੋਣ ਵਾਲਾ ਤਾਪਮਾਨ',
      humidity: 'ਨਮੀ',
      windSpeed: 'ਹਵਾ ਦੀ ਰਫ਼ਤਾਰ',
      pressure: 'ਹਵਾ ਦਾ ਦਬਾਅ',
      uvIndex: 'ਯੂਵੀ ਇੰਡੈਕਸ',
      rainProb: 'ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ',
      cloudCover: 'ਬੱਦਲਵਾਈ',
      airQuality: 'ਹਵਾ ਦੀ ਗੁਣਵੱਤਾ (AQI)',
      visibility: 'ਦਿੱਖ ਸੀਮਾ',
      dewPoint: 'ਤ੍ਰੇਲ ਬਿੰਦੂ',
      soilTemp: 'ਮਿੱਟੀ ਦਾ ਤਾਪਮਾਨ',
    },
    alertLevels: {
      red: 'ਰੈੱਡ ਅਲਰਟ - ਗੰਭੀਰ ਖ਼ਤਰਾ',
      orange: 'ਔਰੇਂਜ ਅਲਰਟ - ਤਿਆਰ ਰਹੋ',
      yellow: 'ਯੈਲੋ ਅਲਰਟ - ਸੁਚੇਤ ਰਹੋ',
      green: 'ਗ੍ਰੀਨ - ਆਮ ਮੌਸਮ',
    },
    prompts: [
      'ਕੀ ਅਗਲੇ 48 ਘੰਟਿਆਂ ਵਿੱਚ ਪੰਜਾਬ ਵਿੱਚ ਮੀਂਹ ਪਵੇਗਾ?',
      'ਕਿਸਾਨਾਂ ਲਈ ਕਣਕ/ਝੋਨੇ ਦੀ ਫਸਲ ਸੁਰੱਖਿਆ ਅਤੇ ਮਿੱਟੀ ਦੀ ਨਮੀ ਸਲਾਹ',
      'ਹਵਾ ਦੀ ਗੁਣਵੱਤਾ (AQI) ਅਤੇ ਧੁੰਦ ਸੰਬੰਧੀ ਚੇਤਾਵਨੀ',
    ]
  }
};
