import React, { useRef } from 'react';
import { X, Printer, Download, FileText, CheckCircle2, ShieldAlert } from 'lucide-react';
import { generateAgriAdvisory, generateAviationBriefing, generateMarineBriefing } from '../services/weatherService';

export default function ReportExportModal({ isOpen, onClose, currentLocation, weatherData, aqiData, alerts = [] }) {
  const reportRef = useRef(null);

  if (!isOpen) return null;

  const locName = `${currentLocation?.name || 'Selected Area'}, ${currentLocation?.country || 'India'}`;
  const current = weatherData?.current || {};
  const daily = weatherData?.daily || {};
  const dateStr = new Date().toLocaleString();

  const agri = generateAgriAdvisory(weatherData);
  const aviation = generateAviationBriefing(currentLocation?.name || 'Station', weatherData);
  const marine = generateMarineBriefing(weatherData);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadText = () => {
    const reportText = `=====================================================
WEATHERGPT: METEOROLOGICAL DISPATCH & DISASTER BULLETIN
=====================================================
Target Location: ${locName}
Issued Timestamp: ${dateStr}
Integrated NWP Models: NOAA GFS 0.25° | ECMWF IFS | DWD ICON
Active Data Feeds: Open-Meteo, WAQI Air Telemetry, RainViewer Radar

[1. CURRENT METEOROLOGICAL CONDITIONS]
• Ambient Temperature: ${current.temperature_2m || '--'} °C (Feels like: ${current.apparent_temperature || '--'} °C)
• Relative Humidity: ${current.relative_humidity_2m || '--'} %
• Surface Wind Field: ${current.wind_speed_10m || '--'} km/h (Gusts: ${current.wind_gusts_10m || '--'} km/h)
• Mean Sea Level Pressure: ${current.pressure_msl || current.surface_pressure || 1013} hPa
• Ultraviolet (UV) Index: ${current.uv_index || 5}
• US Air Quality Index (AQI): ${aqiData?.current?.us_aqi || 50}

[2. EARLY DISASTER WARNINGS & HAZARDS]
${alerts.map(a => `• [${a.level.toUpperCase()}] ${a.title}\n  Details: ${a.message}\n  Directive: ${a.action}`).join('\n\n')}

[3. AGRICULTURAL & CROP ADVISORY]
• Root-Zone Soil Moisture: ${agri?.soilMoisturePercent || '--'} %
• Spray Suitability: ${agri?.sprayCondition || 'Optimal'} (${agri?.sprayAdvice || ''})
• Irrigation Guidance: ${agri?.irrigationAdvice || ''}

[4. AVIATION & METAR BRIEFING]
• Raw METAR: ${aviation?.metar || 'N/A'}
• Flight Category: ${aviation?.flightCategory || 'VFR'}
• Visibility: ${aviation?.visibilityKm || 10} km | Ceiling: ${aviation?.ceilingFeet || 5000} ft AGL

[5. MARINE & COASTAL BRIEFING]
• Significant Wave Amplitude: ${marine?.waveHeightM || 0.8} m
• Sea Classification: ${marine?.seaState || 'Moderate'}
• Vessel Guidance: ${marine?.fishermanAdvisory || 'Safe for navigation'}
=====================================================
Generated by WeatherGPT Autonomous Meteorological AI
=====================================================`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `WeatherGPT_Bulletin_${(currentLocation?.name || 'Weather').replace(/\s+/g, '_')}_${Date.now()}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/40 backdrop-blur-sm animate-fadeIn">
      <div className="w-full max-w-2xl max-h-[90vh] flex flex-col rounded-2xl bg-white border border-slate-200 p-6 shadow-2xl space-y-4">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-200 pb-3">
          <div className="flex items-center space-x-2.5">
            <div className="p-2 rounded-xl bg-sky-50 border border-sky-200 text-sky-600">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900">Export Weather Bulletin & Advisory</h3>
              <p className="text-xs text-slate-500">Standardized Meteorological Report for {locName}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Printable Report Preview */}
        <div ref={reportRef} className="flex-1 overflow-y-auto p-4 rounded-xl bg-slate-50 border border-slate-200 text-xs text-slate-800 space-y-4 font-mono">
          <div className="text-center border-b border-slate-200 pb-3">
            <h2 className="text-base font-bold text-slate-900 font-sans">WEATHERSTUDIO METEOROLOGICAL DISPATCH</h2>
            <div className="text-[11px] text-sky-700 font-bold mt-0.5">Location: {locName}</div>
            <div className="text-[10px] text-slate-500">Generated: {dateStr}</div>
          </div>

          <div>
            <div className="font-bold text-sky-800 mb-1 font-sans">1. Current Atmospheric Metrics:</div>
            <div>• Temperature: {current.temperature_2m}°C (Feels like: {current.apparent_temperature}°C)</div>
            <div>• Relative Humidity: {current.relative_humidity_2m}% | Pressure: {current.pressure_msl || 1013} hPa</div>
            <div>• Wind Velocity: {current.wind_speed_10m} km/h (Gusts: {current.wind_gusts_10m} km/h)</div>
            <div>• Air Quality Index: {aqiData?.current?.us_aqi || 50} (US AQI)</div>
          </div>

          <div>
            <div className="font-bold text-amber-700 mb-1 font-sans">2. Active Disaster Warning Level:</div>
            {alerts.map((a, i) => (
              <div key={i} className="pl-2 border-l-2 border-amber-500 my-1 text-slate-700">
                <span className="font-bold uppercase text-slate-900">[{a.level}] {a.title}</span>: {a.message}
              </div>
            ))}
          </div>

          <div>
            <div className="font-bold text-emerald-700 mb-1 font-sans">3. Agriculture & Sector Directives:</div>
            <div>• Soil Moisture: {agri?.soilMoisturePercent}% | Spray: {agri?.sprayCondition}</div>
            <div>• Irrigation: {agri?.irrigationAdvice}</div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-end space-x-3 pt-3 border-t border-slate-200">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-xs font-medium text-slate-600 hover:text-slate-900 hover:bg-slate-100"
          >
            Close
          </button>
          <button
            onClick={handleDownloadText}
            className="px-4 py-2 rounded-xl text-xs font-bold bg-white hover:bg-slate-50 text-slate-700 border border-slate-300 flex items-center space-x-1.5 shadow-sm"
          >
            <Download className="w-4 h-4" />
            <span>Download .TXT Bulletin</span>
          </button>
          <button
            onClick={handlePrint}
            className="px-5 py-2 rounded-xl text-xs font-bold bg-sky-600 hover:bg-sky-700 text-white shadow-sm flex items-center space-x-1.5"
          >
            <Printer className="w-4 h-4" />
            <span>Print Report</span>
          </button>
        </div>
      </div>
    </div>
  );
}
